version: "3.7"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - 4444:4444
    environment:
      - TZ=Europe/Amsterdam
      - GRID_TIMEOUT=90
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901-5950:5900
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - TZ=Europe/Amsterdam
      - SCREEN_WIDTH=1600
      - SCREEN_HEIGHT=900
    volumes:
      - /dev/shm:/dev/shm # significantly improves tab stability
      - ./shared:/tmp/shared
      - ./shared:/home/seluser/Downloads
      - ./src/main/resources:/tmp/resources
    privileged: true
  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 5951-6000:5900
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - TZ=Europe/Amsterdam
      - SCREEN_WIDTH=1600
      - SCREEN_HEIGHT=900
    volumes:
      - /dev/shm:/dev/shm # significantly improves tab stability
      - ./shared:/tmp/shared
      - ./shared:/home/seluser/Downloads
      - ./src/main/resources:/tmp/resources
    privileged: true
  samsung_galaxy_web_7.1.1:
    image: budtmo/docker-android-x86-10.0
    privileged: true
    depends_on:
      - selenium-hub
    ports:
      - 6080:6080
    volumes:
      - ./src/main/resources:/tmp/resources
      - ./src/app:/tmp/app
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium-hub
      - MOBILE_WEB_TEST=true